### ISSUE TITLE
does this code support the vehicle detecting on the youtube video show?

### ISSUE THREAD

**Issue by gogov5** [baidut/OpenVehicleVision#67]
hi, great open work, 
I want to know does this code support the vehicle detecting on the youtube video show?
thanks

**Comment by baidut** [comment]
Not yet.
Vehicle detection in the youtube video show employs [Faster-RCNN](https://github.com/ShaoqingRen/faster_rcnn) with a little modification.
Related code is not available yet.

**Comment by gogov5** [comment]
Thanks for your information, Qiang
Hope to see you get more progress on this open source project.
